# Generated by Django 5.0.2 on 2024-11-10 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pharmacie', '0002_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
